FROM ubuntu:24.04

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y sudo curl git

RUN mkdir /workspace && chown -R ubuntu:ubuntu /workspace
RUN passwd -d ubuntu

USER ubuntu
RUN curl -fsSL https://opencode.ai/install | bash
RUN curl -LsSf https://astral.sh/uv/install.sh | sh

ENV PATH="$PATH:~/.opencode/bin"
WORKDIR /workspace

RUN sudo apt-get install -y wget