"""
Regression test for the PyScript `packages` config generated by
`ServerApplication.serve`.

For the CPython/Pyodide interpreter (`interpreter = "py"`), the generated
client bootstrap code (embedded in the page) calls
`bootstrap_client(..., deps=self.client_libraries)`, which does
`import micropip; await micropip.install(list(deps))` whenever an app
declares `client_libraries`. Pyodide does not auto-load `micropip` — it
must be requested like any other package — so unless "micropip" is
itself listed in the PyScript `packages` config, that `import micropip`
raises `ModuleNotFoundError` at runtime for any app with non-empty
`client_libraries` (e.g. `("numpy",)`).
"""

import json

import pytest

from pyplet.server._server import BaseHandler, ServerApplication


class _FakeHandler(BaseHandler):
    path_args = ("myproj", "myapp")

    def __init__(self):
        self.application = type("A", (), {"settings": {}})()

    def write(self, chunk):
        self.written = chunk


def _rendered_html(app: ServerApplication) -> str:
    handler = _FakeHandler()
    app.serve(handler)
    return str(handler.written)


def _py_config(html: str) -> dict:
    marker = "config='"
    start = html.index(marker) + len(marker)
    end = html.index("'", start)
    return json.loads(html[start:end])


@pytest.mark.unit
class TestPyScriptPackagesConfig:
    def test_pyodide_packages_include_micropip(self):
        """`micropip` must be preloaded for pyodide apps so the runtime
        `import micropip` in `bootstrap_client` succeeds."""

        class PyApp(ServerApplication):
            interpreter = "py"
            client_libraries = ("numpy",)

        html = _rendered_html(PyApp())
        packages = _py_config(html)["packages"]

        assert "micropip" in packages
        assert "htpy" in packages
        assert "markupsafe" in packages

    def test_pyodide_packages_include_micropip_even_without_deps(self):
        """Baseline packages (including micropip) are always present for
        the pyodide interpreter, regardless of `client_libraries`, matching
        how "htpy"/"markupsafe" are already unconditionally included."""

        class PyAppNoDeps(ServerApplication):
            interpreter = "py"

        html = _rendered_html(PyAppNoDeps())
        packages = _py_config(html)["packages"]

        assert "micropip" in packages

    def test_micropython_packages_stay_empty(self):
        """MicroPython doesn't use micropip (it uses `mip` at runtime via
        `bootstrap_client`'s micropython branch), so its PyScript
        `packages` config must remain empty."""

        class MpyApp(ServerApplication):
            interpreter = "mpy"
            client_libraries = ("numpy",)

        html = _rendered_html(MpyApp())
        packages = _py_config(html)["packages"]

        assert packages == []
